[build]
  command = "npm run build"
  publish = ".next"

# Configurações de ambiente
[context.production]
  environment = { NODE_VERSION = "18", NEXT_PRIVATE_TARGET = "server" }

# Plugin para otimizar o deploy do Next.js no Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"
